# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bertin/CLionProjects/COEN244

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bertin/CLionProjects/COEN244

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bertin/CLionProjects/COEN244/CMakeFiles /Users/bertin/CLionProjects/COEN244//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bertin/CLionProjects/COEN244/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named binary_math

# Build rule for target.
binary_math: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 binary_math
.PHONY : binary_math

# fast build rule for target.
binary_math/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_math.dir/build.make CMakeFiles/binary_math.dir/build
.PHONY : binary_math/fast

#=============================================================================
# Target rules for targets named Time

# Build rule for target.
Time: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Time
.PHONY : Time

# fast build rule for target.
Time/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time.dir/build.make CMakeFiles/Time.dir/build
.PHONY : Time/fast

#=============================================================================
# Target rules for targets named main2

# Build rule for target.
main2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main2
.PHONY : main2

# fast build rule for target.
main2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/build
.PHONY : main2/fast

#=============================================================================
# Target rules for targets named regex

# Build rule for target.
regex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 regex
.PHONY : regex

# fast build rule for target.
regex/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/build
.PHONY : regex/fast

#=============================================================================
# Target rules for targets named CLI

# Build rule for target.
CLI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CLI
.PHONY : CLI

# fast build rule for target.
CLI/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLI.dir/build.make CMakeFiles/CLI.dir/build
.PHONY : CLI/fast

#=============================================================================
# Target rules for targets named macros

# Build rule for target.
macros: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 macros
.PHONY : macros

# fast build rule for target.
macros/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/macros.dir/build.make CMakeFiles/macros.dir/build
.PHONY : macros/fast

#=============================================================================
# Target rules for targets named Ass4

# Build rule for target.
Ass4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Ass4
.PHONY : Ass4

# fast build rule for target.
Ass4/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4.dir/build.make CMakeFiles/Ass4.dir/build
.PHONY : Ass4/fast

#=============================================================================
# Target rules for targets named Ass4-2

# Build rule for target.
Ass4-2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Ass4-2
.PHONY : Ass4-2

# fast build rule for target.
Ass4-2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4-2.dir/build.make CMakeFiles/Ass4-2.dir/build
.PHONY : Ass4-2/fast

#=============================================================================
# Target rules for targets named Ass4-3

# Build rule for target.
Ass4-3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Ass4-3
.PHONY : Ass4-3

# fast build rule for target.
Ass4-3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4-3.dir/build.make CMakeFiles/Ass4-3.dir/build
.PHONY : Ass4-3/fast

#=============================================================================
# Target rules for targets named streams

# Build rule for target.
streams: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 streams
.PHONY : streams

# fast build rule for target.
streams/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streams.dir/build.make CMakeFiles/streams.dir/build
.PHONY : streams/fast

#=============================================================================
# Target rules for targets named Board

# Build rule for target.
Board: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Board
.PHONY : Board

# fast build rule for target.
Board/fast:
	$(MAKE) $(MAKESILENT) -f A3/CMakeFiles/Board.dir/build.make A3/CMakeFiles/Board.dir/build
.PHONY : Board/fast

#=============================================================================
# Target rules for targets named Player

# Build rule for target.
Player: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Player
.PHONY : Player

# fast build rule for target.
Player/fast:
	$(MAKE) $(MAKESILENT) -f A3/CMakeFiles/Player.dir/build.make A3/CMakeFiles/Player.dir/build
.PHONY : Player/fast

#=============================================================================
# Target rules for targets named Othello

# Build rule for target.
Othello: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Othello
.PHONY : Othello

# fast build rule for target.
Othello/fast:
	$(MAKE) $(MAKESILENT) -f A3/CMakeFiles/Othello.dir/build.make A3/CMakeFiles/Othello.dir/build
.PHONY : Othello/fast

CLI.o: CLI.cpp.o
.PHONY : CLI.o

# target to build an object file
CLI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLI.dir/build.make CMakeFiles/CLI.dir/CLI.cpp.o
.PHONY : CLI.cpp.o

CLI.i: CLI.cpp.i
.PHONY : CLI.i

# target to preprocess a source file
CLI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLI.dir/build.make CMakeFiles/CLI.dir/CLI.cpp.i
.PHONY : CLI.cpp.i

CLI.s: CLI.cpp.s
.PHONY : CLI.s

# target to generate assembly for a file
CLI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLI.dir/build.make CMakeFiles/CLI.dir/CLI.cpp.s
.PHONY : CLI.cpp.s

binary_math.o: binary_math.cpp.o
.PHONY : binary_math.o

# target to build an object file
binary_math.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_math.dir/build.make CMakeFiles/binary_math.dir/binary_math.cpp.o
.PHONY : binary_math.cpp.o

binary_math.i: binary_math.cpp.i
.PHONY : binary_math.i

# target to preprocess a source file
binary_math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_math.dir/build.make CMakeFiles/binary_math.dir/binary_math.cpp.i
.PHONY : binary_math.cpp.i

binary_math.s: binary_math.cpp.s
.PHONY : binary_math.s

# target to generate assembly for a file
binary_math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_math.dir/build.make CMakeFiles/binary_math.dir/binary_math.cpp.s
.PHONY : binary_math.cpp.s

foreign/assignment4-q1.o: foreign/assignment4-q1.cpp.o
.PHONY : foreign/assignment4-q1.o

# target to build an object file
foreign/assignment4-q1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4.dir/build.make CMakeFiles/Ass4.dir/foreign/assignment4-q1.cpp.o
.PHONY : foreign/assignment4-q1.cpp.o

foreign/assignment4-q1.i: foreign/assignment4-q1.cpp.i
.PHONY : foreign/assignment4-q1.i

# target to preprocess a source file
foreign/assignment4-q1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4.dir/build.make CMakeFiles/Ass4.dir/foreign/assignment4-q1.cpp.i
.PHONY : foreign/assignment4-q1.cpp.i

foreign/assignment4-q1.s: foreign/assignment4-q1.cpp.s
.PHONY : foreign/assignment4-q1.s

# target to generate assembly for a file
foreign/assignment4-q1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4.dir/build.make CMakeFiles/Ass4.dir/foreign/assignment4-q1.cpp.s
.PHONY : foreign/assignment4-q1.cpp.s

foreign/assignment4-q2/employee.o: foreign/assignment4-q2/employee.cpp.o
.PHONY : foreign/assignment4-q2/employee.o

# target to build an object file
foreign/assignment4-q2/employee.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4-2.dir/build.make CMakeFiles/Ass4-2.dir/foreign/assignment4-q2/employee.cpp.o
.PHONY : foreign/assignment4-q2/employee.cpp.o

foreign/assignment4-q2/employee.i: foreign/assignment4-q2/employee.cpp.i
.PHONY : foreign/assignment4-q2/employee.i

# target to preprocess a source file
foreign/assignment4-q2/employee.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4-2.dir/build.make CMakeFiles/Ass4-2.dir/foreign/assignment4-q2/employee.cpp.i
.PHONY : foreign/assignment4-q2/employee.cpp.i

foreign/assignment4-q2/employee.s: foreign/assignment4-q2/employee.cpp.s
.PHONY : foreign/assignment4-q2/employee.s

# target to generate assembly for a file
foreign/assignment4-q2/employee.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4-2.dir/build.make CMakeFiles/Ass4-2.dir/foreign/assignment4-q2/employee.cpp.s
.PHONY : foreign/assignment4-q2/employee.cpp.s

foreign/assignment4-q2/testemployee.o: foreign/assignment4-q2/testemployee.cpp.o
.PHONY : foreign/assignment4-q2/testemployee.o

# target to build an object file
foreign/assignment4-q2/testemployee.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4-2.dir/build.make CMakeFiles/Ass4-2.dir/foreign/assignment4-q2/testemployee.cpp.o
.PHONY : foreign/assignment4-q2/testemployee.cpp.o

foreign/assignment4-q2/testemployee.i: foreign/assignment4-q2/testemployee.cpp.i
.PHONY : foreign/assignment4-q2/testemployee.i

# target to preprocess a source file
foreign/assignment4-q2/testemployee.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4-2.dir/build.make CMakeFiles/Ass4-2.dir/foreign/assignment4-q2/testemployee.cpp.i
.PHONY : foreign/assignment4-q2/testemployee.cpp.i

foreign/assignment4-q2/testemployee.s: foreign/assignment4-q2/testemployee.cpp.s
.PHONY : foreign/assignment4-q2/testemployee.s

# target to generate assembly for a file
foreign/assignment4-q2/testemployee.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4-2.dir/build.make CMakeFiles/Ass4-2.dir/foreign/assignment4-q2/testemployee.cpp.s
.PHONY : foreign/assignment4-q2/testemployee.cpp.s

foreign/assignment4-q3/department.o: foreign/assignment4-q3/department.cpp.o
.PHONY : foreign/assignment4-q3/department.o

# target to build an object file
foreign/assignment4-q3/department.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4-3.dir/build.make CMakeFiles/Ass4-3.dir/foreign/assignment4-q3/department.cpp.o
.PHONY : foreign/assignment4-q3/department.cpp.o

foreign/assignment4-q3/department.i: foreign/assignment4-q3/department.cpp.i
.PHONY : foreign/assignment4-q3/department.i

# target to preprocess a source file
foreign/assignment4-q3/department.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4-3.dir/build.make CMakeFiles/Ass4-3.dir/foreign/assignment4-q3/department.cpp.i
.PHONY : foreign/assignment4-q3/department.cpp.i

foreign/assignment4-q3/department.s: foreign/assignment4-q3/department.cpp.s
.PHONY : foreign/assignment4-q3/department.s

# target to generate assembly for a file
foreign/assignment4-q3/department.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4-3.dir/build.make CMakeFiles/Ass4-3.dir/foreign/assignment4-q3/department.cpp.s
.PHONY : foreign/assignment4-q3/department.cpp.s

foreign/assignment4-q3/employee.o: foreign/assignment4-q3/employee.cpp.o
.PHONY : foreign/assignment4-q3/employee.o

# target to build an object file
foreign/assignment4-q3/employee.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4-3.dir/build.make CMakeFiles/Ass4-3.dir/foreign/assignment4-q3/employee.cpp.o
.PHONY : foreign/assignment4-q3/employee.cpp.o

foreign/assignment4-q3/employee.i: foreign/assignment4-q3/employee.cpp.i
.PHONY : foreign/assignment4-q3/employee.i

# target to preprocess a source file
foreign/assignment4-q3/employee.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4-3.dir/build.make CMakeFiles/Ass4-3.dir/foreign/assignment4-q3/employee.cpp.i
.PHONY : foreign/assignment4-q3/employee.cpp.i

foreign/assignment4-q3/employee.s: foreign/assignment4-q3/employee.cpp.s
.PHONY : foreign/assignment4-q3/employee.s

# target to generate assembly for a file
foreign/assignment4-q3/employee.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4-3.dir/build.make CMakeFiles/Ass4-3.dir/foreign/assignment4-q3/employee.cpp.s
.PHONY : foreign/assignment4-q3/employee.cpp.s

foreign/assignment4-q3/testdepartment.o: foreign/assignment4-q3/testdepartment.cpp.o
.PHONY : foreign/assignment4-q3/testdepartment.o

# target to build an object file
foreign/assignment4-q3/testdepartment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4-3.dir/build.make CMakeFiles/Ass4-3.dir/foreign/assignment4-q3/testdepartment.cpp.o
.PHONY : foreign/assignment4-q3/testdepartment.cpp.o

foreign/assignment4-q3/testdepartment.i: foreign/assignment4-q3/testdepartment.cpp.i
.PHONY : foreign/assignment4-q3/testdepartment.i

# target to preprocess a source file
foreign/assignment4-q3/testdepartment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4-3.dir/build.make CMakeFiles/Ass4-3.dir/foreign/assignment4-q3/testdepartment.cpp.i
.PHONY : foreign/assignment4-q3/testdepartment.cpp.i

foreign/assignment4-q3/testdepartment.s: foreign/assignment4-q3/testdepartment.cpp.s
.PHONY : foreign/assignment4-q3/testdepartment.s

# target to generate assembly for a file
foreign/assignment4-q3/testdepartment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass4-3.dir/build.make CMakeFiles/Ass4-3.dir/foreign/assignment4-q3/testdepartment.cpp.s
.PHONY : foreign/assignment4-q3/testdepartment.cpp.s

macros.o: macros.cpp.o
.PHONY : macros.o

# target to build an object file
macros.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/macros.dir/build.make CMakeFiles/macros.dir/macros.cpp.o
.PHONY : macros.cpp.o

macros.i: macros.cpp.i
.PHONY : macros.i

# target to preprocess a source file
macros.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/macros.dir/build.make CMakeFiles/macros.dir/macros.cpp.i
.PHONY : macros.cpp.i

macros.s: macros.cpp.s
.PHONY : macros.s

# target to generate assembly for a file
macros.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/macros.dir/build.make CMakeFiles/macros.dir/macros.cpp.s
.PHONY : macros.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

main2.o: main2.cpp.o
.PHONY : main2.o

# target to build an object file
main2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/main2.cpp.o
.PHONY : main2.cpp.o

main2.i: main2.cpp.i
.PHONY : main2.i

# target to preprocess a source file
main2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/main2.cpp.i
.PHONY : main2.cpp.i

main2.s: main2.cpp.s
.PHONY : main2.s

# target to generate assembly for a file
main2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/main2.cpp.s
.PHONY : main2.cpp.s

regex.o: regex.cpp.o
.PHONY : regex.o

# target to build an object file
regex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/regex.cpp.o
.PHONY : regex.cpp.o

regex.i: regex.cpp.i
.PHONY : regex.i

# target to preprocess a source file
regex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/regex.cpp.i
.PHONY : regex.cpp.i

regex.s: regex.cpp.s
.PHONY : regex.s

# target to generate assembly for a file
regex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/regex.cpp.s
.PHONY : regex.cpp.s

streams.o: streams.cpp.o
.PHONY : streams.o

# target to build an object file
streams.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streams.dir/build.make CMakeFiles/streams.dir/streams.cpp.o
.PHONY : streams.cpp.o

streams.i: streams.cpp.i
.PHONY : streams.i

# target to preprocess a source file
streams.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streams.dir/build.make CMakeFiles/streams.dir/streams.cpp.i
.PHONY : streams.cpp.i

streams.s: streams.cpp.s
.PHONY : streams.s

# target to generate assembly for a file
streams.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streams.dir/build.make CMakeFiles/streams.dir/streams.cpp.s
.PHONY : streams.cpp.s

time.o: time.cpp.o
.PHONY : time.o

# target to build an object file
time.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time.dir/build.make CMakeFiles/Time.dir/time.cpp.o
.PHONY : time.cpp.o

time.i: time.cpp.i
.PHONY : time.i

# target to preprocess a source file
time.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time.dir/build.make CMakeFiles/Time.dir/time.cpp.i
.PHONY : time.cpp.i

time.s: time.cpp.s
.PHONY : time.s

# target to generate assembly for a file
time.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Time.dir/build.make CMakeFiles/Time.dir/time.cpp.s
.PHONY : time.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Ass4"
	@echo "... Ass4-2"
	@echo "... Ass4-3"
	@echo "... Board"
	@echo "... CLI"
	@echo "... Othello"
	@echo "... Player"
	@echo "... Time"
	@echo "... binary_math"
	@echo "... macros"
	@echo "... main"
	@echo "... main2"
	@echo "... regex"
	@echo "... streams"
	@echo "... CLI.o"
	@echo "... CLI.i"
	@echo "... CLI.s"
	@echo "... binary_math.o"
	@echo "... binary_math.i"
	@echo "... binary_math.s"
	@echo "... foreign/assignment4-q1.o"
	@echo "... foreign/assignment4-q1.i"
	@echo "... foreign/assignment4-q1.s"
	@echo "... foreign/assignment4-q2/employee.o"
	@echo "... foreign/assignment4-q2/employee.i"
	@echo "... foreign/assignment4-q2/employee.s"
	@echo "... foreign/assignment4-q2/testemployee.o"
	@echo "... foreign/assignment4-q2/testemployee.i"
	@echo "... foreign/assignment4-q2/testemployee.s"
	@echo "... foreign/assignment4-q3/department.o"
	@echo "... foreign/assignment4-q3/department.i"
	@echo "... foreign/assignment4-q3/department.s"
	@echo "... foreign/assignment4-q3/employee.o"
	@echo "... foreign/assignment4-q3/employee.i"
	@echo "... foreign/assignment4-q3/employee.s"
	@echo "... foreign/assignment4-q3/testdepartment.o"
	@echo "... foreign/assignment4-q3/testdepartment.i"
	@echo "... foreign/assignment4-q3/testdepartment.s"
	@echo "... macros.o"
	@echo "... macros.i"
	@echo "... macros.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... main2.o"
	@echo "... main2.i"
	@echo "... main2.s"
	@echo "... regex.o"
	@echo "... regex.i"
	@echo "... regex.s"
	@echo "... streams.o"
	@echo "... streams.i"
	@echo "... streams.s"
	@echo "... time.o"
	@echo "... time.i"
	@echo "... time.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

